directory = "./img"

[auth]
consumer_key = ""
consumer_secret = ""
oauth_token = ""
oauth_secret = ""

[notification]
enable = true

[notification.desktop]
enable = true

[notification.discord]
enable = false
webhookUrl = ""

[notification.discord.mention]
enable = false
discordId = ""